### ISSUE TITLE
Players are not transferred

### ISSUE THREAD

**Issue by TonyDroidd** [shoghicp/FastTransfer#1]
The console say:
[INFO] Transferring player TonyDroidd to play.nexuspe.net:19132
but the players are not transferred...

**Comment by RekkuzaRage** [comment]
I don't think the plugin works yet

**Comment by TonyDroidd** [comment]
If @shoghicp  throw the first release, that means it works ...

**Comment by Gamecrafter** [comment]
Maybe it's a beta release. Haven't you ever thought of that? -.-

**Comment by TonyDroidd** [comment]
Yes, but i say it to shoghi, you're not shoghi :)

**Comment by Gamecrafter** [comment]
LOL

**Comment by TonyDroidd** [comment]
Yes.

**Comment by RekkuzaRage** [comment]
Lol. LBSG already saw this project coming, they are currently working on a new lobby that most likely use FastTransfer to connect their servers...

**Comment by Gamecrafter** [comment]
Probably not FastTransfer, though. @williamtdr might just code his own.

**Comment by MobileCrafter** [comment]
"Transfer vanilla Minecraft: PE clients to another server. Works with Minecraft: PE 0.11.0 alpha build 6 or higher."
Look at the build.
We just have to wait until build 6 is released ;)
