### ISSUE TITLE
Doesn't work on newer pocketmine builds

### ISSUE THREAD

**Issue by thelucyclub** [shoghicp/FastTransfer#10]
Doesn't work on newer pocketmine builds. :hankey: 
I use MiNET instead its like a beta Bungee-Cord for PE but still. I use to use this a lot. Now I cant.
Hope its fixed soon! BTW I blame @shoghicp for the pocketmine php7 thingy ma bobber

**Comment by shoghicp** [comment]
This is not a problem of the plugin, this only used a feature available on older MCPE releases
