### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by MinerGirl98** [shoghicp/FastTransfer#4]
Hi I'm new to having a server and need help. When I get the simple Auth plugin it tells me that I have to register and that I have the wrong password. So when I uninstall the plug in I can go on my server but nobody else can join. I'm a noob at servers please help. Trying to make this for my website. Thanks, Shannon

**Comment by TonyDroidd** [comment]
You are in the wrong place ...

**Comment by MinerGirl98** [comment]
Oh boy.. sorry I told you I was a noob at servers. I'm just trying to get a server together for a website I write articles for. And there's a lot of people in the community that want to join and I don't know much about servers. Where am I suppose to go if I'm in the wrong place? Thanks

**Comment by MinerGirl98** [comment]
I see now. I didn't mean to put this on Shoghi's fast transfer post...

**Comment by iksaku** [comment]
To set-up a server use "googl" ;)

**Comment by MinerGirl98** [comment]
Yes I have used Google but having a problem with simple Auth. I'm not a tech savy person. I don't understand coding. I'm a nurse..llol
